version: "2.1"

services:
  database:
    container_name: database
    image: mongo:3.6.4
    restart: always   
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./database/entrypoint/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    environment:
      - NODE_ENV=development
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=fHYmOGIIsjBxbvcp
    healthcheck:
      test: mongo --eval "db.runCommand('ping').ok"
      interval: 5s
      timeout: 5s
      retries: 12
    networks:
      disid-network:
        aliases:
          - mongo

volumes:
  mongo-data:
    name: mongo-data
      
networks:
  disid-network:
    external:
      name: disid-network
